# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170609_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('author', models.CharField(max_length=40)),
                ('text', redactor.fields.RedactorField(verbose_name='Comment')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=redactor.fields.RedactorField(verbose_name='Blog Post'),
        ),
        migrations.AddField(
            model_name='blogpostcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.BlogPost'),
        ),
        migrations.AlterUniqueTogether(
            name='blogpostcomment',
            unique_together=set([('email', 'author')]),
        ),
    ]
