# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_blogpost_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
