# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=utils.get_file_path)),
                ('footer', redactor.fields.RedactorField()),
                ('about', redactor.fields.RedactorField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
